# Generated by Django 5.2.6 on 2025-10-30 17:22

import colorfield.fields
import django.db.models.deletion
import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0017_usersocialauth_user_social_auth_uid_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField()),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField(max_length=500, null=True)),
                ('min', models.PositiveIntegerField(blank=True, null=True)),
                ('max', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_students', models.CharField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('links', models.JSONField(blank=True, default=list, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClinicMatchApp.major')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.CharField()),
                ('crn', models.PositiveIntegerField(blank=True, null=True)),
                ('current_clinic', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='Active_Clinic', to='ClinicMatchApp.clinic')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClinicMatchApp.major')),
                ('prev_clinics', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='Previous_Clinics', to='ClinicMatchApp.clinic')),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_mgmt',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='professor_list', to='ClinicMatchApp.professor'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(max_length=500)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ClinicMatchApp.professor')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='prof_reviews',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='prof_review_history', to='ClinicMatchApp.review'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(null=True)),
                ('last_name', models.CharField(null=True)),
                ('email', models.CharField(null=True)),
                ('banner_id', models.PositiveIntegerField(null=True)),
                ('j_or_s', models.CharField(blank=True, choices=[('J', 'Junior'), ('S', 'Senior')], max_length=1, null=True)),
                ('assigned_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_Output', to='ClinicMatchApp.clinic')),
                ('choices', sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='Students_top_8_Choices', to='ClinicMatchApp.clinic')),
                ('initial_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Initial_Assignments', to='ClinicMatchApp.clinic')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClinicMatchApp.major')),
                ('userAuth', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth')),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='current_students',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='current_students_in_clinic', to='ClinicMatchApp.student'),
        ),
        migrations.CreateModel(
            name='ClinicNumberHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.BooleanField(default=False)),
                ('min', models.PositiveIntegerField(blank=True, null=True)),
                ('max', models.PositiveIntegerField(blank=True, null=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numberHandler', to='ClinicMatchApp.clinic')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClinicMatchApp.major')),
            ],
            options={
                'unique_together': {('clinic', 'major')},
            },
        ),
    ]
