# Generated by Django 5.2.6 on 2025-10-06 22:57

import django.db.models.deletion
import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField(max_length=500, null=True)),
                ('min', models.PositiveIntegerField(blank=True, null=True)),
                ('max', models.PositiveIntegerField(blank=True, null=True)),
                ('links', models.CharField(blank=True, null=True)),
                ('requestedStudents', models.CharField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClinicMatchApp.major')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.CharField()),
                ('currentClinic', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='Active_Clinic', to='ClinicMatchApp.clinic')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClinicMatchApp.major')),
                ('prev_clinics', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='Previous_Clinics', to='ClinicMatchApp.clinic')),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_mgmt',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='professor_list', to='ClinicMatchApp.professor'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(max_length=500)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ClinicMatchApp.professor')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='prof_reviews',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='prof_review_history', to='ClinicMatchApp.review'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.CharField()),
                ('bannerID', models.FloatField()),
                ('j_or_s', models.CharField(choices=[('J', 'Junior'), ('S', 'Senior')])),
                ('assignedClinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_Output', to='ClinicMatchApp.clinic')),
                ('choices', sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='Students_top_8_Choices', to='ClinicMatchApp.clinic')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClinicMatchApp.major')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicNumberHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.BooleanField(default=False)),
                ('min', models.PositiveIntegerField(blank=True, null=True)),
                ('max', models.PositiveIntegerField(blank=True, null=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numberHandler', to='ClinicMatchApp.clinic')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClinicMatchApp.major')),
            ],
            options={
                'unique_together': {('clinic', 'major')},
            },
        ),
    ]
