# Generated by Django 5.2.6 on 2025-09-28 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.CharField()),
                ('bannerID', models.FloatField()),
                ('j_or_s', models.CharField(choices=[('J', 'Junior'), ('S', 'Senior')])),
                ('assignedClinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_Output', to='ClinicMatchApp.clinic')),
                ('choices', models.ManyToManyField(related_name='Students_top_8_Choices', to='ClinicMatchApp.clinic')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClinicMatchApp.major')),
            ],
        ),
    ]
