# Generated by Django 5.2.6 on 2025-10-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0001_initial'),
        ('social_django', '0017_usersocialauth_user_social_auth_uid_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='userAuth',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth'),
        ),
    ]
