# Generated by Django 5.2.6 on 2025-11-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alternative_major',
            field=models.BooleanField(default=False),
        ),
    ]
