# Generated by Django 5.2.6 on 2025-11-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='clinicImages/'),
        ),
    ]
