# Generated by Django 5.2.6 on 2025-10-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='requestedStudents',
            new_name='requested_students',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='currentClinic',
            new_name='current_clinic',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='assignedClinic',
            new_name='assigned_clinic',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='bannerID',
            new_name='banner_id',
        ),
    ]
