# Generated by Django 5.2.6 on 2025-09-28 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClinicMatchApp.major'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ClinicNumberHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.PositiveIntegerField(blank=True, null=True)),
                ('max', models.PositiveIntegerField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_requirements', to='ClinicMatchApp.clinic')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClinicMatchApp.major')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('email', models.CharField()),
                ('currentClinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Active_Clinic', to='ClinicMatchApp.clinic')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClinicMatchApp.major')),
                ('prev_clinics', models.ManyToManyField(related_name='Previous_Clinics', to='ClinicMatchApp.clinic')),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_mgmt',
            field=models.ManyToManyField(related_name='professor_list', to='ClinicMatchApp.professor'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(max_length=500)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ClinicMatchApp.professor')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='prof_reviews',
            field=models.ManyToManyField(related_name='prof_review_history', to='ClinicMatchApp.reviews'),
        ),
    ]
