# Generated by Django 5.2.6 on 2025-10-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0002_rename_requestedstudents_clinic_requested_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='banner_id',
            field=models.PositiveIntegerField(),
        ),
    ]
