# Generated by Django 5.2.6 on 2025-11-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0002_alter_clinic_image'),
        ('ClinicMatchApp', '0002_student_alternative_major'),
    ]

    operations = [
    ]
