# Generated by Django 5.2.6 on 2025-11-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0003_merge_20251106_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorCodeStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField()),
                ('code', models.CharField()),
            ],
        ),
    ]
