# Generated by Django 5.2.6 on 2025-10-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0003_alter_student_banner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='crn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
