# Generated by Django 5.2.6 on 2025-09-30 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0003_rename_reviews_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='currentClinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Active_Clinic', to='ClinicMatchApp.clinic'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='prev_clinics',
            field=models.ManyToManyField(blank=True, null=True, related_name='Previous_Clinics', to='ClinicMatchApp.clinic'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='prof_reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='prof_review_history', to='ClinicMatchApp.review'),
        ),
    ]
