# Generated by Django 5.2.6 on 2025-10-08 17:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0004_professor_crn'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
