# Generated by Django 5.2.6 on 2025-09-30 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0004_alter_professor_currentclinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assignedClinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_Output', to='ClinicMatchApp.clinic'),
        ),
    ]
