# Generated by Django 5.2.6 on 2025-09-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0005_alter_student_assignedclinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='currentClinic',
        ),
        migrations.AddField(
            model_name='professor',
            name='currentClinic',
            field=models.ManyToManyField(blank=True, null=True, related_name='Active_Clinic', to='ClinicMatchApp.clinic'),
        ),
    ]
