# Generated by Django 5.2.6 on 2025-11-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0005_delete_professorcodestorage_professor_userauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='pop_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
