# Generated by Django 5.2.6 on 2025-11-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0005_delete_professorcodestorage_professor_userauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='link',
            field=models.CharField(null=True),
        ),
    ]
