# Generated by Django 5.2.6 on 2025-10-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0002_student_userauth'),
        ('ClinicMatchApp', '0005_major_color'),
    ]

    operations = [
    ]
