# Generated by Django 5.2.6 on 2025-09-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0006_remove_professor_currentclinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinic_mgmt',
            field=models.ManyToManyField(blank=True, null=True, related_name='professor_list', to='ClinicMatchApp.professor'),
        ),
    ]
