# Generated by Django 5.2.6 on 2025-10-20 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0006_merge_0002_student_userauth_0005_major_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='j_or_s',
            field=models.CharField(blank=True, choices=[('J', 'Junior'), ('S', 'Senior')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClinicMatchApp.major'),
        ),
    ]
