# Generated by Django 5.2.6 on 2025-11-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0006_clinic_pop_index'),
        ('ClinicMatchApp', '0006_student_link'),
    ]

    operations = [
    ]
