# Generated by Django 5.2.6 on 2025-11-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0007_merge_0006_clinic_pop_index_0006_student_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_externally_funded',
            field=models.BooleanField(default=0),
        ),
    ]
