# Generated by Django 5.2.6 on 2025-09-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0007_alter_clinic_clinic_mgmt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicnumberhandler',
            name='clinic',
        ),
    ]
