# Generated by Django 5.2.6 on 2025-10-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0007_alter_student_j_or_s_alter_student_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='banner_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(null=True),
        ),
    ]
