# Generated by Django 5.2.6 on 2025-10-23 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0008_alter_student_banner_id_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='initial_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Initial_Assignments', to='ClinicMatchApp.clinic'),
        ),
    ]
