# Generated by Django 5.2.6 on 2025-12-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0008_clinic_is_externally_funded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicnumberhandler',
            name='max',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clinicnumberhandler',
            name='min',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
