# Generated by Django 5.2.6 on 2025-10-23 15:34

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0009_student_initial_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='current_students',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='current_students_in_clinic', to='ClinicMatchApp.student'),
        ),
    ]
