# Generated by Django 5.2.6 on 2025-09-30 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0009_clinicnumberhandler_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicnumberhandler',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numberHandler', to='ClinicMatchApp.clinic'),
        ),
    ]
