# Generated by Django 5.2.6 on 2025-10-01 14:20

import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0010_alter_clinicnumberhandler_clinic'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='clinic',
            name='clinic_mgmt',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='professor_list', to='ClinicMatchApp.professor'),
        ),
        AlterSortedManyToManyField(
            model_name='professor',
            name='currentClinic',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='Active_Clinic', to='ClinicMatchApp.clinic'),
        ),
        AlterSortedManyToManyField(
            model_name='professor',
            name='prev_clinics',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='Previous_Clinics', to='ClinicMatchApp.clinic'),
        ),
        AlterSortedManyToManyField(
            model_name='professor',
            name='prof_reviews',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, related_name='prof_review_history', to='ClinicMatchApp.review'),
        ),
        AlterSortedManyToManyField(
            model_name='student',
            name='choices',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='Students_top_8_Choices', to='ClinicMatchApp.clinic'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicnumberhandler',
            unique_together={('clinic', 'major')},
        ),
    ]
