# Generated by Django 5.2.6 on 2025-10-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0010_clinic_current_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clinic',
            name='links',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
