# Generated by Django 5.2.6 on 2025-10-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0011_alter_clinic_clinic_mgmt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='requestedStudents',
            field=models.CharField(blank=True, null=True),
        ),
    ]
