# Generated by Django 5.2.6 on 2025-10-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0012_clinic_requestedstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
