# Generated by Django 5.2.6 on 2025-10-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0013_clinic_max_clinic_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicnumberhandler',
            name='general',
            field=models.BooleanField(default=False),
        ),
    ]
