# Generated by Django 5.2.6 on 2025-10-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicMatchApp', '0014_clinicnumberhandler_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='links',
            field=models.CharField(blank=True, null=True),
        ),
    ]
